import { MigrationInterface, QueryRunner } from "typeorm";

export class TenantDb1778059182050 implements MigrationInterface {
    name = 'TenantDb1778059182050'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "permissions" ("id" SERIAL NOT NULL, "code" character varying NOT NULL, "name" character varying NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_8dad765629e83229da6feda1c1d" UNIQUE ("code"), CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying NOT NULL, "name" character varying NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_f6d54f95c31b73fb1bdd8e91d0c" UNIQUE ("code"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "title" text NOT NULL, "message" text NOT NULL, "type" text NOT NULL, "isRead" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "regions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "cityId" character varying NOT NULL, "name" character varying(150) NOT NULL, "code" character varying(50), "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4fcd12ed6a046276e2deb08801c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_1ab3aa79ae29d7f99f17c9a4a7" ON "regions" ("cityId", "name") `);
        await queryRunner.query(`CREATE TYPE "public"."pjp_plans_status_enum" AS ENUM('PENDING', 'ACTIVE', 'INACTIVE')`);
        await queryRunner.query(`CREATE TABLE "pjp_plans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "weekStartDate" TIMESTAMP NOT NULL, "weekEndDate" TIMESTAMP NOT NULL, "salesmanId" uuid, "status" "public"."pjp_plans_status_enum" NOT NULL DEFAULT 'PENDING', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_733235c53432523eb945e47c84b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "pjp_routes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "pjpId" uuid NOT NULL, "routeId" uuid NOT NULL, "visitDate" TIMESTAMP NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5ab28cddd60fb772a8c1592fccb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "purchase_stocks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "distributorId" uuid NOT NULL, "remarks" character varying NOT NULL, "purchaseDate" TIMESTAMP NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_502fddb5cbcd4e5d0c0866de730" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "purchase_stock_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "purchaseStockId" uuid NOT NULL, "productId" uuid NOT NULL, "productFlavourId" integer NOT NULL, "productPricingId" uuid NOT NULL, "quantity" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_500ecef392c3d5b714b0a092ef8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "opening_stocks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "distributorId" uuid NOT NULL, "remarks" character varying NOT NULL, "Date" TIMESTAMP NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" uuid, CONSTRAINT "PK_f0a32dc9bd57b7a9f143fbb12a2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "opening_stock_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "OpeningStockId" uuid NOT NULL, "productId" uuid NOT NULL, "productFlavourId" integer NOT NULL, "productPricingId" uuid NOT NULL, "quantity" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5e1620df26c0372aa50e24c7857" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."stock_movements_type_enum" AS ENUM('IN', 'OUT')`);
        await queryRunner.query(`CREATE TYPE "public"."stock_movements_referencetype_enum" AS ENUM('ADJUSTMENT', 'TRANSFER', 'PURCHASE', 'OPENING', 'LOAD', 'DELIVERY', 'RETURN', 'SALE')`);
        await queryRunner.query(`CREATE TABLE "stock_movements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "distributorId" uuid NOT NULL, "productId" uuid NOT NULL, "productFlavourId" integer NOT NULL, "productPricingId" uuid NOT NULL, "quantity" integer NOT NULL, "type" "public"."stock_movements_type_enum" NOT NULL, "referenceType" "public"."stock_movements_referencetype_enum" NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_57a26b190618550d8e65fb860e7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "stock_balances" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "distributorId" uuid NOT NULL, "productId" uuid NOT NULL, "productFlavourId" integer NOT NULL, "productPricingId" uuid NOT NULL, "quantity" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4c0d249ce58f9a559eb7df31b23" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "stock_transfers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fromDistributorId" uuid NOT NULL, "toDistributorId" uuid NOT NULL, "remarks" character varying NOT NULL, "transferDate" TIMESTAMP NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ef738a3a4a578c7f1802c1bb50a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "stock_transfer_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "StockTransferId" uuid NOT NULL, "productId" uuid NOT NULL, "productFlavourId" integer NOT NULL, "productPricingId" uuid NOT NULL, "quantity" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8acee6121ab8a5135dc84495588" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "slug" character varying NOT NULL, "created_by" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7069dac60d88408eca56fdc9e0c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "flavours" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_58d10322f711a67c1c70a8d0820" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "uoms" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "is_base" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_f207a792064e3032c8fe3922b22" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_brands" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f2b98a8f25bd37b19c8356ec659" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "products" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "categoryId" uuid NOT NULL, "skuCode" character varying NOT NULL, "name" character varying NOT NULL, "hsCode" character varying, "description" character varying, "brandId" uuid, "image" character varying, "isActive" boolean NOT NULL DEFAULT true, "isDelete" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" uuid, CONSTRAINT "UQ_65ac74fb678576a4a9865d7eaf6" UNIQUE ("skuCode"), CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_flavours" ("id" SERIAL NOT NULL, "productId" uuid NOT NULL, "flavourId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_52de19df846c67e8a3614664d5d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_pricings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "productId" uuid NOT NULL, "uomId" uuid NOT NULL, "tradePrice" character varying NOT NULL, "retailPrice" character varying NOT NULL, "quantity" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b02e2444e19a69760718a1c6eeb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_pricing_jobs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "productId" uuid NOT NULL, "productPricingId" uuid NOT NULL, "startDate" TIMESTAMP NOT NULL, "status" character varying NOT NULL, "tradePrice" character varying NOT NULL, "retailPrice" character varying NOT NULL, "quantity" integer NOT NULL, "errorMessage" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e12966075c7f49d527c8772ae8a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "schemes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "schemeType" character varying NOT NULL, "benefitType" character varying NOT NULL, "startDate" TIMESTAMP NOT NULL, "endDate" TIMESTAMP NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "isDeleted" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_fd989991874a1aab8856e326cd3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "scheme_slabs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "minQuantity" integer NOT NULL, "maxQuantity" integer NOT NULL, "benefitValue" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "schemeId" uuid, CONSTRAINT "PK_bbffa086392eabeee0996261f10" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "scheme_retailers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "schemeId" uuid, "retailerId" uuid, CONSTRAINT "PK_d2fdbad1273ab92fb82fea4dc6a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "scheme_retailer_channels" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "schemeId" uuid, "retailerChannelId" uuid, CONSTRAINT "PK_8fc0cf311779b4bcddc461ee9b3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "scheme_products" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "productPricingId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "schemeId" uuid, "productId" uuid, CONSTRAINT "PK_71ddcce79f09ad71436fce13fb4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "scheme_product_categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "schemeId" uuid, "productCategoryId" uuid, CONSTRAINT "PK_76138d5742098aad6659c12de75" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "retailer_categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7e395337e17d0cba314dd0f0eec" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "retailer_channels" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_393d8c324fe4965ad911b25fe37" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."retailers_class_enum" AS ENUM('A', 'B', 'C')`);
        await queryRunner.query(`CREATE TYPE "public"."retailers_status_enum" AS ENUM('ACTIVE', 'INACTIVE', 'PENDING')`);
        await queryRunner.query(`CREATE TABLE "retailers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "shopName" character varying NOT NULL, "ownerName" character varying NOT NULL, "image" character varying, "Phone" character varying, "Email" character varying, "CNIC" character varying, "STRN" character varying, "NTN" character varying, "Address" character varying NOT NULL, "latitude" character varying NOT NULL, "longitude" character varying NOT NULL, "maxRadius" character varying NOT NULL, "creditLimit" character varying NOT NULL, "class" "public"."retailers_class_enum" NOT NULL, "status" "public"."retailers_status_enum" NOT NULL, "createdBy" uuid NOT NULL, "approvedBy" uuid, "routeId" uuid NOT NULL, "retailerCategoryId" uuid NOT NULL, "retailerChannelId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1228653999402b52e75d40b1c66" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."retailer_ledgers_reftype_enum" AS ENUM('SALE', 'RETURN', 'PAYMENT')`);
        await queryRunner.query(`CREATE TABLE "retailer_ledgers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "retailerId" uuid NOT NULL, "refType" "public"."retailer_ledgers_reftype_enum" NOT NULL, "credit" character varying, "debit" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2e1f94213ed33d5cba51f007594" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."sale_orders_orderstatus_enum" AS ENUM('PENDING', 'APPROVED', 'REJECTED', 'PROCESSING', 'CANCELLED', 'DELIVERED')`);
        await queryRunner.query(`CREATE TABLE "sale_orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "orderNumber" character varying NOT NULL, "distributorId" uuid NOT NULL, "salesmanId" uuid NOT NULL, "retailerId" uuid NOT NULL, "routeId" uuid NOT NULL, "orderStatus" "public"."sale_orders_orderstatus_enum" NOT NULL, "orderTotal" integer NOT NULL, "taxPercentage" integer NOT NULL DEFAULT '0', "taxAmount" integer NOT NULL DEFAULT '0', "discountPercentage" integer NOT NULL DEFAULT '0', "discountAmount" integer NOT NULL DEFAULT '0', "totalAmount" integer NOT NULL DEFAULT '0', "schemeId" uuid, "schemeSlabId" uuid, "notes" character varying, "executedBy" uuid, "orderDate" TIMESTAMP NOT NULL, "executedDate" TIMESTAMP, "deliveredDate" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_ca1959beef162c2ccace1481cec" UNIQUE ("orderNumber"), CONSTRAINT "PK_ba301b7939d3333e8821ff92637" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sale_order_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "saleOrderId" uuid NOT NULL, "productId" uuid NOT NULL, "productFlavourId" integer NOT NULL, "productPricingId" uuid NOT NULL, "schemeId" uuid, "slabId" uuid, "quantity" integer NOT NULL, "discountPercentage" integer NOT NULL DEFAULT '0', "discountAmount" integer NOT NULL DEFAULT '0', "totalAmount" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6c46724b3d93b4c233ca288871a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "routes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "areaId" uuid NOT NULL, "distributorId" uuid NOT NULL, "name" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_76100511cdfa1d013c859f01d8b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "route_transfer_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fromSalesmanId" uuid NOT NULL, "toSalesmanId" uuid NOT NULL, "pjpId" uuid NOT NULL, "routeId" uuid NOT NULL, "transferDate" TIMESTAMP NOT NULL, "reason" character varying NOT NULL, "remarks" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_37f64c5195a905013e85e5c4e04" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "route_shares" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "routeId" uuid NOT NULL, "fromSalesmanId" uuid NOT NULL, "toSalesmanId" uuid NOT NULL, "visitDate" TIMESTAMP NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4970fd6c3a0aa3f73068e4f89e6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "areas" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "code" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "regionId" uuid, CONSTRAINT "PK_5110493f6342f34c978c084d0d6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."attendences_status_enum" AS ENUM('PRESENT', 'ABSENT', 'LEAVE', 'WORK_FROM_HOME', 'REMOTE')`);
        await queryRunner.query(`CREATE TABLE "attendences" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "distributorId" uuid NOT NULL, "attendenceDate" TIMESTAMP NOT NULL, "checkInLocation" character varying, "checkInTime" TIMESTAMP, "checkInLatitude" integer, "checkInLongitude" integer, "checkOutLocation" character varying, "checkOutTime" TIMESTAMP, "checkOutLatitude" integer, "checkOutLongitude" integer, "status" "public"."attendences_status_enum" NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_48b8e690d65013c58b030901166" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "attendence_tracking_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "attendenceId" uuid NOT NULL, "latitude" integer NOT NULL, "longitude" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_907957baf5f4d1e275e142510a8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "distributors" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "code" character varying NOT NULL, "email" character varying, "phone" character varying NOT NULL, "address" character varying NOT NULL, "countryId" character varying, "stateId" character varying, "cityId" character varying, "postalCode" character varying NOT NULL, "locationTitle" character varying NOT NULL, "latitude" character varying NOT NULL, "longitude" character varying NOT NULL, "maxRadius" character varying NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "isDeleted" boolean NOT NULL DEFAULT false, "stockLock" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "areaId" uuid, CONSTRAINT "PK_a3741291eb0af96f795b25d90b4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "designations" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "slug" character varying NOT NULL, "description" character varying, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a0f024b99b1491a03fc421858ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying NOT NULL, "name" character varying NOT NULL, "email" character varying NOT NULL, "password" character varying, "phone" character varying, "cnic" character varying, "avatar" character varying, "address" character varying, "designationId" integer, "joiningDate" TIMESTAMP, "leavingDate" TIMESTAMP, "countryId" character varying, "stateId" character varying, "cityId" character varying, "isActive" boolean NOT NULL DEFAULT true, "isDeleted" boolean NOT NULL DEFAULT false, "roleId" uuid, "deviceId" character varying, "fcmToken" character varying, "locationTitle" character varying, "latitude" character varying, "longitude" character varying, "maxRadius" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_1f7a2b11e29b1422a2622beab36" UNIQUE ("code"), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "salesman_distributors" ("id" SERIAL NOT NULL, "userId" uuid, "distributorId" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_dd7553ddfbbf53b5059265e66fd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."assets_status_enum" AS ENUM('PENDING', 'APPROVED', 'REJECTED')`);
        await queryRunner.query(`CREATE TABLE "assets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "uploadedById" uuid, "purpose" character varying NOT NULL, "s3Key" character varying NOT NULL, "entityType" character varying, "entityId" character varying, "originalFileName" character varying NOT NULL, "fileExtension" character varying NOT NULL, "fileSize" integer NOT NULL, "status" "public"."assets_status_enum" NOT NULL, "confirmedAt" TIMESTAMP, "attachedAt" TIMESTAMP, "deletedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_da96729a8b113377cfb6a62439c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "activity_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "actorId" uuid, "action" character varying NOT NULL, "description" text, "metadata" jsonb, "jobId" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f25287b6140c5ba18d38776a796" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rolePermissions" ("roleId" uuid NOT NULL, "permissionId" integer NOT NULL, CONSTRAINT "PK_9e7ab7e8aec914fa1886f6fa632" PRIMARY KEY ("roleId", "permissionId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b20f4ad2fcaa0d311f92516267" ON "rolePermissions" ("roleId") `);
        await queryRunner.query(`CREATE INDEX "IDX_5cb213a16a7b5204c8aff88151" ON "rolePermissions" ("permissionId") `);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_692a909ee0fa9383e7859f9b406" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pjp_plans" ADD CONSTRAINT "FK_70e9fef610a86676c398ae41062" FOREIGN KEY ("salesmanId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pjp_routes" ADD CONSTRAINT "FK_0fefe4771f11f44fafd4622cfb6" FOREIGN KEY ("pjpId") REFERENCES "pjp_plans"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pjp_routes" ADD CONSTRAINT "FK_4decedea8a8df76a8c52bea0906" FOREIGN KEY ("routeId") REFERENCES "routes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_stocks" ADD CONSTRAINT "FK_b0c114bd76c1707c722cb4de7e5" FOREIGN KEY ("distributorId") REFERENCES "distributors"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_stock_items" ADD CONSTRAINT "FK_2f8e01ed95178e218b624b4bb89" FOREIGN KEY ("purchaseStockId") REFERENCES "purchase_stocks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_stock_items" ADD CONSTRAINT "FK_fe00198bdd975ba01b9122ad159" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_stock_items" ADD CONSTRAINT "FK_b6bcb012d13d64ae3bee1e3bb1e" FOREIGN KEY ("productFlavourId") REFERENCES "product_flavours"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_stock_items" ADD CONSTRAINT "FK_3ead6f3aee294292edad5d1cae9" FOREIGN KEY ("productPricingId") REFERENCES "product_pricings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "opening_stocks" ADD CONSTRAINT "FK_9d8598e48ff94dfe1c709f9dcab" FOREIGN KEY ("distributorId") REFERENCES "distributors"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "opening_stocks" ADD CONSTRAINT "FK_d02837a6e2eb14f39c850333b33" FOREIGN KEY ("createdBy") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "opening_stock_items" ADD CONSTRAINT "FK_05638fc63251751725f0b647031" FOREIGN KEY ("OpeningStockId") REFERENCES "opening_stocks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "opening_stock_items" ADD CONSTRAINT "FK_6758aa05c5e9f66354b6c25fbda" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "opening_stock_items" ADD CONSTRAINT "FK_baa8d6f7141b134a541ddd51c25" FOREIGN KEY ("productFlavourId") REFERENCES "product_flavours"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "opening_stock_items" ADD CONSTRAINT "FK_b15678fc23e9884ad2cf2d5663c" FOREIGN KEY ("productPricingId") REFERENCES "product_pricings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ADD CONSTRAINT "FK_36b5a7d45d6a01c642eb0531aac" FOREIGN KEY ("distributorId") REFERENCES "distributors"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ADD CONSTRAINT "FK_a3acb59db67e977be45e382fc56" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ADD CONSTRAINT "FK_fa1dc98c1b1e4688d0d49a694fd" FOREIGN KEY ("productFlavourId") REFERENCES "product_flavours"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ADD CONSTRAINT "FK_8fd1e90f53f77732a8ea464da37" FOREIGN KEY ("productPricingId") REFERENCES "product_pricings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_balances" ADD CONSTRAINT "FK_5978797fdc3e297c2c67c288757" FOREIGN KEY ("distributorId") REFERENCES "distributors"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_balances" ADD CONSTRAINT "FK_6840607b19b9f629d9c6845f31c" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_balances" ADD CONSTRAINT "FK_53c9974de6f1d1581bd7998445c" FOREIGN KEY ("productFlavourId") REFERENCES "product_flavours"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_balances" ADD CONSTRAINT "FK_9f933ebe19686b338e1b3277ac1" FOREIGN KEY ("productPricingId") REFERENCES "product_pricings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_transfers" ADD CONSTRAINT "FK_4f7c2a31ce918de1f122b9e9ea1" FOREIGN KEY ("fromDistributorId") REFERENCES "distributors"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_transfers" ADD CONSTRAINT "FK_707314286019327054dda97576c" FOREIGN KEY ("toDistributorId") REFERENCES "distributors"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_transfer_items" ADD CONSTRAINT "FK_99f2530758c959cd8d5b18f91a1" FOREIGN KEY ("StockTransferId") REFERENCES "stock_transfers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_transfer_items" ADD CONSTRAINT "FK_f3d2b9e6f306fc4a292c687a12d" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_transfer_items" ADD CONSTRAINT "FK_b330dd3d94732f0398be5c9eb1d" FOREIGN KEY ("productFlavourId") REFERENCES "product_flavours"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_transfer_items" ADD CONSTRAINT "FK_c459a3dd06d1149012669481e44" FOREIGN KEY ("productPricingId") REFERENCES "product_pricings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_categories" ADD CONSTRAINT "FK_66bf1d237f3576eeae37ac1b2eb" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_ff56834e735fa78a15d0cf21926" FOREIGN KEY ("categoryId") REFERENCES "product_categories"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_ea86d0c514c4ecbb5694cbf57df" FOREIGN KEY ("brandId") REFERENCES "product_brands"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_f74bae41998e06cc579f081ea78" FOREIGN KEY ("createdBy") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_flavours" ADD CONSTRAINT "FK_a0282b16f9daac2e15112340566" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_flavours" ADD CONSTRAINT "FK_a08a13461af44625ec0bff252f4" FOREIGN KEY ("flavourId") REFERENCES "flavours"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_pricings" ADD CONSTRAINT "FK_b43a68bd3e947aa98a89f45aa66" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_pricings" ADD CONSTRAINT "FK_d6c3496a0f0db19c58282f97e2a" FOREIGN KEY ("uomId") REFERENCES "uoms"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_pricing_jobs" ADD CONSTRAINT "FK_2c90c83e94881af1f566f5249e4" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_pricing_jobs" ADD CONSTRAINT "FK_9674e21a39bdf7d08d5ad247eac" FOREIGN KEY ("productPricingId") REFERENCES "product_pricings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scheme_slabs" ADD CONSTRAINT "FK_b5e1dacbd30abc943f300aff24c" FOREIGN KEY ("schemeId") REFERENCES "schemes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scheme_retailers" ADD CONSTRAINT "FK_2ff46e6dc504a2233865d79d6ea" FOREIGN KEY ("schemeId") REFERENCES "schemes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scheme_retailers" ADD CONSTRAINT "FK_b42757ade560f8b316335a8e46e" FOREIGN KEY ("retailerId") REFERENCES "retailers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scheme_retailer_channels" ADD CONSTRAINT "FK_3faf7b2396d49b04f6954465f03" FOREIGN KEY ("schemeId") REFERENCES "schemes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scheme_retailer_channels" ADD CONSTRAINT "FK_9ac1a9b5246a5d38dc7dc1dadb3" FOREIGN KEY ("retailerChannelId") REFERENCES "retailer_channels"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scheme_products" ADD CONSTRAINT "FK_f1c874ce29353f84b9a0b2e8765" FOREIGN KEY ("schemeId") REFERENCES "schemes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scheme_products" ADD CONSTRAINT "FK_f4da17978009525ac11d95ed2da" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scheme_products" ADD CONSTRAINT "FK_70a85dc3710a03cc037e8f2735b" FOREIGN KEY ("productPricingId") REFERENCES "product_pricings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scheme_product_categories" ADD CONSTRAINT "FK_5dca945160dbcb6b396a167d7d7" FOREIGN KEY ("schemeId") REFERENCES "schemes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scheme_product_categories" ADD CONSTRAINT "FK_75c10c62da0ce974732bd76dad2" FOREIGN KEY ("productCategoryId") REFERENCES "product_categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "retailers" ADD CONSTRAINT "FK_4d12073533cb8395e686a125eee" FOREIGN KEY ("createdBy") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "retailers" ADD CONSTRAINT "FK_e5e845d6015c8a18d843ce7b630" FOREIGN KEY ("approvedBy") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "retailers" ADD CONSTRAINT "FK_58d6c6a4048dae0340b17146a47" FOREIGN KEY ("routeId") REFERENCES "routes"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "retailers" ADD CONSTRAINT "FK_2df00191c2b7fdee5c7a5421d6d" FOREIGN KEY ("retailerCategoryId") REFERENCES "retailer_categories"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "retailers" ADD CONSTRAINT "FK_c249afceaa25eff4411aeea9750" FOREIGN KEY ("retailerChannelId") REFERENCES "retailer_channels"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "retailer_ledgers" ADD CONSTRAINT "FK_f8abb09f406f647034790511edd" FOREIGN KEY ("retailerId") REFERENCES "retailers"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_orders" ADD CONSTRAINT "FK_c2c3628be596f219d2b24446988" FOREIGN KEY ("distributorId") REFERENCES "distributors"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_orders" ADD CONSTRAINT "FK_fa3d2c4fecf3295858c9d25e7af" FOREIGN KEY ("salesmanId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_orders" ADD CONSTRAINT "FK_ea0e9727c2adc940bf21c51a30a" FOREIGN KEY ("retailerId") REFERENCES "retailers"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_orders" ADD CONSTRAINT "FK_a183f0cf5dd1185b29a64964288" FOREIGN KEY ("routeId") REFERENCES "routes"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_orders" ADD CONSTRAINT "FK_2cbe851e9f5bd96eb7316fc5284" FOREIGN KEY ("schemeId") REFERENCES "schemes"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_orders" ADD CONSTRAINT "FK_c7875800aad762a3472e6c8aaad" FOREIGN KEY ("schemeSlabId") REFERENCES "scheme_slabs"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_orders" ADD CONSTRAINT "FK_ea532a6a0fa3c1714f36a6d5090" FOREIGN KEY ("executedBy") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_order_items" ADD CONSTRAINT "FK_d49fcbd1de0d711c2c7e98a0e4b" FOREIGN KEY ("saleOrderId") REFERENCES "sale_orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_order_items" ADD CONSTRAINT "FK_1449ab76dc9e3f75a472539904e" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_order_items" ADD CONSTRAINT "FK_8771927a21dd3d9ddc7cbfdd3d0" FOREIGN KEY ("productFlavourId") REFERENCES "product_flavours"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_order_items" ADD CONSTRAINT "FK_5d3209fc10079eef01bbf4161b8" FOREIGN KEY ("productPricingId") REFERENCES "product_pricings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_order_items" ADD CONSTRAINT "FK_a673602010c8c70aacc36cd8f22" FOREIGN KEY ("schemeId") REFERENCES "schemes"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_order_items" ADD CONSTRAINT "FK_a27eeaa0031f95961743445eb44" FOREIGN KEY ("slabId") REFERENCES "scheme_slabs"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "routes" ADD CONSTRAINT "FK_a8507b496096dd547189ec98af2" FOREIGN KEY ("areaId") REFERENCES "areas"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "routes" ADD CONSTRAINT "FK_03484907485e7037f88ede88b90" FOREIGN KEY ("distributorId") REFERENCES "distributors"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "route_transfer_logs" ADD CONSTRAINT "FK_b05e79dfe6eed2e3883e1ac6505" FOREIGN KEY ("fromSalesmanId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "route_transfer_logs" ADD CONSTRAINT "FK_eb49ee9bde9ef03608f87c2334f" FOREIGN KEY ("toSalesmanId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "route_transfer_logs" ADD CONSTRAINT "FK_c2867e069b87f5cbf96a3a78455" FOREIGN KEY ("pjpId") REFERENCES "pjp_plans"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "route_transfer_logs" ADD CONSTRAINT "FK_05a95f898698820517eef5c5e85" FOREIGN KEY ("routeId") REFERENCES "routes"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "route_shares" ADD CONSTRAINT "FK_d12b12fc5e6294e288ee1a1cbf9" FOREIGN KEY ("routeId") REFERENCES "routes"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "route_shares" ADD CONSTRAINT "FK_805d98d4b47f00fe8ed20a19af1" FOREIGN KEY ("fromSalesmanId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "route_shares" ADD CONSTRAINT "FK_b1289b96a502887e5abe6505c25" FOREIGN KEY ("toSalesmanId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "areas" ADD CONSTRAINT "FK_87d7ab74bea8551a1be41d1056f" FOREIGN KEY ("regionId") REFERENCES "regions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendences" ADD CONSTRAINT "FK_90aa572566b545c62b074b52fde" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendences" ADD CONSTRAINT "FK_5ad40a1c21b726cdd0cb9dfdcc7" FOREIGN KEY ("distributorId") REFERENCES "distributors"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendence_tracking_logs" ADD CONSTRAINT "FK_31411d3e74b122cac1a943bfb23" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendence_tracking_logs" ADD CONSTRAINT "FK_0b2761316875f4587bd1dfd1f12" FOREIGN KEY ("attendenceId") REFERENCES "attendences"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "distributors" ADD CONSTRAINT "FK_e5620b921daa1088ac510d0f023" FOREIGN KEY ("areaId") REFERENCES "areas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_071a5e4a3131d00a0fc700af411" FOREIGN KEY ("designationId") REFERENCES "designations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_368e146b785b574f42ae9e53d5e" FOREIGN KEY ("roleId") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "salesman_distributors" ADD CONSTRAINT "FK_037a2ae28b82ef35d37558a0d60" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "salesman_distributors" ADD CONSTRAINT "FK_31e455e65a8a050cb678697d49d" FOREIGN KEY ("distributorId") REFERENCES "distributors"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assets" ADD CONSTRAINT "FK_b9fdc4600fb5785205eb8ebef55" FOREIGN KEY ("uploadedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ADD CONSTRAINT "FK_110bb0d32b7f65be46be37e2577" FOREIGN KEY ("actorId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rolePermissions" ADD CONSTRAINT "FK_b20f4ad2fcaa0d311f925162675" FOREIGN KEY ("roleId") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "rolePermissions" ADD CONSTRAINT "FK_5cb213a16a7b5204c8aff881518" FOREIGN KEY ("permissionId") REFERENCES "permissions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "rolePermissions" DROP CONSTRAINT "FK_5cb213a16a7b5204c8aff881518"`);
        await queryRunner.query(`ALTER TABLE "rolePermissions" DROP CONSTRAINT "FK_b20f4ad2fcaa0d311f925162675"`);
        await queryRunner.query(`ALTER TABLE "activity_logs" DROP CONSTRAINT "FK_110bb0d32b7f65be46be37e2577"`);
        await queryRunner.query(`ALTER TABLE "assets" DROP CONSTRAINT "FK_b9fdc4600fb5785205eb8ebef55"`);
        await queryRunner.query(`ALTER TABLE "salesman_distributors" DROP CONSTRAINT "FK_31e455e65a8a050cb678697d49d"`);
        await queryRunner.query(`ALTER TABLE "salesman_distributors" DROP CONSTRAINT "FK_037a2ae28b82ef35d37558a0d60"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_368e146b785b574f42ae9e53d5e"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_071a5e4a3131d00a0fc700af411"`);
        await queryRunner.query(`ALTER TABLE "distributors" DROP CONSTRAINT "FK_e5620b921daa1088ac510d0f023"`);
        await queryRunner.query(`ALTER TABLE "attendence_tracking_logs" DROP CONSTRAINT "FK_0b2761316875f4587bd1dfd1f12"`);
        await queryRunner.query(`ALTER TABLE "attendence_tracking_logs" DROP CONSTRAINT "FK_31411d3e74b122cac1a943bfb23"`);
        await queryRunner.query(`ALTER TABLE "attendences" DROP CONSTRAINT "FK_5ad40a1c21b726cdd0cb9dfdcc7"`);
        await queryRunner.query(`ALTER TABLE "attendences" DROP CONSTRAINT "FK_90aa572566b545c62b074b52fde"`);
        await queryRunner.query(`ALTER TABLE "areas" DROP CONSTRAINT "FK_87d7ab74bea8551a1be41d1056f"`);
        await queryRunner.query(`ALTER TABLE "route_shares" DROP CONSTRAINT "FK_b1289b96a502887e5abe6505c25"`);
        await queryRunner.query(`ALTER TABLE "route_shares" DROP CONSTRAINT "FK_805d98d4b47f00fe8ed20a19af1"`);
        await queryRunner.query(`ALTER TABLE "route_shares" DROP CONSTRAINT "FK_d12b12fc5e6294e288ee1a1cbf9"`);
        await queryRunner.query(`ALTER TABLE "route_transfer_logs" DROP CONSTRAINT "FK_05a95f898698820517eef5c5e85"`);
        await queryRunner.query(`ALTER TABLE "route_transfer_logs" DROP CONSTRAINT "FK_c2867e069b87f5cbf96a3a78455"`);
        await queryRunner.query(`ALTER TABLE "route_transfer_logs" DROP CONSTRAINT "FK_eb49ee9bde9ef03608f87c2334f"`);
        await queryRunner.query(`ALTER TABLE "route_transfer_logs" DROP CONSTRAINT "FK_b05e79dfe6eed2e3883e1ac6505"`);
        await queryRunner.query(`ALTER TABLE "routes" DROP CONSTRAINT "FK_03484907485e7037f88ede88b90"`);
        await queryRunner.query(`ALTER TABLE "routes" DROP CONSTRAINT "FK_a8507b496096dd547189ec98af2"`);
        await queryRunner.query(`ALTER TABLE "sale_order_items" DROP CONSTRAINT "FK_a27eeaa0031f95961743445eb44"`);
        await queryRunner.query(`ALTER TABLE "sale_order_items" DROP CONSTRAINT "FK_a673602010c8c70aacc36cd8f22"`);
        await queryRunner.query(`ALTER TABLE "sale_order_items" DROP CONSTRAINT "FK_5d3209fc10079eef01bbf4161b8"`);
        await queryRunner.query(`ALTER TABLE "sale_order_items" DROP CONSTRAINT "FK_8771927a21dd3d9ddc7cbfdd3d0"`);
        await queryRunner.query(`ALTER TABLE "sale_order_items" DROP CONSTRAINT "FK_1449ab76dc9e3f75a472539904e"`);
        await queryRunner.query(`ALTER TABLE "sale_order_items" DROP CONSTRAINT "FK_d49fcbd1de0d711c2c7e98a0e4b"`);
        await queryRunner.query(`ALTER TABLE "sale_orders" DROP CONSTRAINT "FK_ea532a6a0fa3c1714f36a6d5090"`);
        await queryRunner.query(`ALTER TABLE "sale_orders" DROP CONSTRAINT "FK_c7875800aad762a3472e6c8aaad"`);
        await queryRunner.query(`ALTER TABLE "sale_orders" DROP CONSTRAINT "FK_2cbe851e9f5bd96eb7316fc5284"`);
        await queryRunner.query(`ALTER TABLE "sale_orders" DROP CONSTRAINT "FK_a183f0cf5dd1185b29a64964288"`);
        await queryRunner.query(`ALTER TABLE "sale_orders" DROP CONSTRAINT "FK_ea0e9727c2adc940bf21c51a30a"`);
        await queryRunner.query(`ALTER TABLE "sale_orders" DROP CONSTRAINT "FK_fa3d2c4fecf3295858c9d25e7af"`);
        await queryRunner.query(`ALTER TABLE "sale_orders" DROP CONSTRAINT "FK_c2c3628be596f219d2b24446988"`);
        await queryRunner.query(`ALTER TABLE "retailer_ledgers" DROP CONSTRAINT "FK_f8abb09f406f647034790511edd"`);
        await queryRunner.query(`ALTER TABLE "retailers" DROP CONSTRAINT "FK_c249afceaa25eff4411aeea9750"`);
        await queryRunner.query(`ALTER TABLE "retailers" DROP CONSTRAINT "FK_2df00191c2b7fdee5c7a5421d6d"`);
        await queryRunner.query(`ALTER TABLE "retailers" DROP CONSTRAINT "FK_58d6c6a4048dae0340b17146a47"`);
        await queryRunner.query(`ALTER TABLE "retailers" DROP CONSTRAINT "FK_e5e845d6015c8a18d843ce7b630"`);
        await queryRunner.query(`ALTER TABLE "retailers" DROP CONSTRAINT "FK_4d12073533cb8395e686a125eee"`);
        await queryRunner.query(`ALTER TABLE "scheme_product_categories" DROP CONSTRAINT "FK_75c10c62da0ce974732bd76dad2"`);
        await queryRunner.query(`ALTER TABLE "scheme_product_categories" DROP CONSTRAINT "FK_5dca945160dbcb6b396a167d7d7"`);
        await queryRunner.query(`ALTER TABLE "scheme_products" DROP CONSTRAINT "FK_70a85dc3710a03cc037e8f2735b"`);
        await queryRunner.query(`ALTER TABLE "scheme_products" DROP CONSTRAINT "FK_f4da17978009525ac11d95ed2da"`);
        await queryRunner.query(`ALTER TABLE "scheme_products" DROP CONSTRAINT "FK_f1c874ce29353f84b9a0b2e8765"`);
        await queryRunner.query(`ALTER TABLE "scheme_retailer_channels" DROP CONSTRAINT "FK_9ac1a9b5246a5d38dc7dc1dadb3"`);
        await queryRunner.query(`ALTER TABLE "scheme_retailer_channels" DROP CONSTRAINT "FK_3faf7b2396d49b04f6954465f03"`);
        await queryRunner.query(`ALTER TABLE "scheme_retailers" DROP CONSTRAINT "FK_b42757ade560f8b316335a8e46e"`);
        await queryRunner.query(`ALTER TABLE "scheme_retailers" DROP CONSTRAINT "FK_2ff46e6dc504a2233865d79d6ea"`);
        await queryRunner.query(`ALTER TABLE "scheme_slabs" DROP CONSTRAINT "FK_b5e1dacbd30abc943f300aff24c"`);
        await queryRunner.query(`ALTER TABLE "product_pricing_jobs" DROP CONSTRAINT "FK_9674e21a39bdf7d08d5ad247eac"`);
        await queryRunner.query(`ALTER TABLE "product_pricing_jobs" DROP CONSTRAINT "FK_2c90c83e94881af1f566f5249e4"`);
        await queryRunner.query(`ALTER TABLE "product_pricings" DROP CONSTRAINT "FK_d6c3496a0f0db19c58282f97e2a"`);
        await queryRunner.query(`ALTER TABLE "product_pricings" DROP CONSTRAINT "FK_b43a68bd3e947aa98a89f45aa66"`);
        await queryRunner.query(`ALTER TABLE "product_flavours" DROP CONSTRAINT "FK_a08a13461af44625ec0bff252f4"`);
        await queryRunner.query(`ALTER TABLE "product_flavours" DROP CONSTRAINT "FK_a0282b16f9daac2e15112340566"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_f74bae41998e06cc579f081ea78"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_ea86d0c514c4ecbb5694cbf57df"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_ff56834e735fa78a15d0cf21926"`);
        await queryRunner.query(`ALTER TABLE "product_categories" DROP CONSTRAINT "FK_66bf1d237f3576eeae37ac1b2eb"`);
        await queryRunner.query(`ALTER TABLE "stock_transfer_items" DROP CONSTRAINT "FK_c459a3dd06d1149012669481e44"`);
        await queryRunner.query(`ALTER TABLE "stock_transfer_items" DROP CONSTRAINT "FK_b330dd3d94732f0398be5c9eb1d"`);
        await queryRunner.query(`ALTER TABLE "stock_transfer_items" DROP CONSTRAINT "FK_f3d2b9e6f306fc4a292c687a12d"`);
        await queryRunner.query(`ALTER TABLE "stock_transfer_items" DROP CONSTRAINT "FK_99f2530758c959cd8d5b18f91a1"`);
        await queryRunner.query(`ALTER TABLE "stock_transfers" DROP CONSTRAINT "FK_707314286019327054dda97576c"`);
        await queryRunner.query(`ALTER TABLE "stock_transfers" DROP CONSTRAINT "FK_4f7c2a31ce918de1f122b9e9ea1"`);
        await queryRunner.query(`ALTER TABLE "stock_balances" DROP CONSTRAINT "FK_9f933ebe19686b338e1b3277ac1"`);
        await queryRunner.query(`ALTER TABLE "stock_balances" DROP CONSTRAINT "FK_53c9974de6f1d1581bd7998445c"`);
        await queryRunner.query(`ALTER TABLE "stock_balances" DROP CONSTRAINT "FK_6840607b19b9f629d9c6845f31c"`);
        await queryRunner.query(`ALTER TABLE "stock_balances" DROP CONSTRAINT "FK_5978797fdc3e297c2c67c288757"`);
        await queryRunner.query(`ALTER TABLE "stock_movements" DROP CONSTRAINT "FK_8fd1e90f53f77732a8ea464da37"`);
        await queryRunner.query(`ALTER TABLE "stock_movements" DROP CONSTRAINT "FK_fa1dc98c1b1e4688d0d49a694fd"`);
        await queryRunner.query(`ALTER TABLE "stock_movements" DROP CONSTRAINT "FK_a3acb59db67e977be45e382fc56"`);
        await queryRunner.query(`ALTER TABLE "stock_movements" DROP CONSTRAINT "FK_36b5a7d45d6a01c642eb0531aac"`);
        await queryRunner.query(`ALTER TABLE "opening_stock_items" DROP CONSTRAINT "FK_b15678fc23e9884ad2cf2d5663c"`);
        await queryRunner.query(`ALTER TABLE "opening_stock_items" DROP CONSTRAINT "FK_baa8d6f7141b134a541ddd51c25"`);
        await queryRunner.query(`ALTER TABLE "opening_stock_items" DROP CONSTRAINT "FK_6758aa05c5e9f66354b6c25fbda"`);
        await queryRunner.query(`ALTER TABLE "opening_stock_items" DROP CONSTRAINT "FK_05638fc63251751725f0b647031"`);
        await queryRunner.query(`ALTER TABLE "opening_stocks" DROP CONSTRAINT "FK_d02837a6e2eb14f39c850333b33"`);
        await queryRunner.query(`ALTER TABLE "opening_stocks" DROP CONSTRAINT "FK_9d8598e48ff94dfe1c709f9dcab"`);
        await queryRunner.query(`ALTER TABLE "purchase_stock_items" DROP CONSTRAINT "FK_3ead6f3aee294292edad5d1cae9"`);
        await queryRunner.query(`ALTER TABLE "purchase_stock_items" DROP CONSTRAINT "FK_b6bcb012d13d64ae3bee1e3bb1e"`);
        await queryRunner.query(`ALTER TABLE "purchase_stock_items" DROP CONSTRAINT "FK_fe00198bdd975ba01b9122ad159"`);
        await queryRunner.query(`ALTER TABLE "purchase_stock_items" DROP CONSTRAINT "FK_2f8e01ed95178e218b624b4bb89"`);
        await queryRunner.query(`ALTER TABLE "purchase_stocks" DROP CONSTRAINT "FK_b0c114bd76c1707c722cb4de7e5"`);
        await queryRunner.query(`ALTER TABLE "pjp_routes" DROP CONSTRAINT "FK_4decedea8a8df76a8c52bea0906"`);
        await queryRunner.query(`ALTER TABLE "pjp_routes" DROP CONSTRAINT "FK_0fefe4771f11f44fafd4622cfb6"`);
        await queryRunner.query(`ALTER TABLE "pjp_plans" DROP CONSTRAINT "FK_70e9fef610a86676c398ae41062"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_692a909ee0fa9383e7859f9b406"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5cb213a16a7b5204c8aff88151"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b20f4ad2fcaa0d311f92516267"`);
        await queryRunner.query(`DROP TABLE "rolePermissions"`);
        await queryRunner.query(`DROP TABLE "activity_logs"`);
        await queryRunner.query(`DROP TABLE "assets"`);
        await queryRunner.query(`DROP TYPE "public"."assets_status_enum"`);
        await queryRunner.query(`DROP TABLE "salesman_distributors"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "designations"`);
        await queryRunner.query(`DROP TABLE "distributors"`);
        await queryRunner.query(`DROP TABLE "attendence_tracking_logs"`);
        await queryRunner.query(`DROP TABLE "attendences"`);
        await queryRunner.query(`DROP TYPE "public"."attendences_status_enum"`);
        await queryRunner.query(`DROP TABLE "areas"`);
        await queryRunner.query(`DROP TABLE "route_shares"`);
        await queryRunner.query(`DROP TABLE "route_transfer_logs"`);
        await queryRunner.query(`DROP TABLE "routes"`);
        await queryRunner.query(`DROP TABLE "sale_order_items"`);
        await queryRunner.query(`DROP TABLE "sale_orders"`);
        await queryRunner.query(`DROP TYPE "public"."sale_orders_orderstatus_enum"`);
        await queryRunner.query(`DROP TABLE "retailer_ledgers"`);
        await queryRunner.query(`DROP TYPE "public"."retailer_ledgers_reftype_enum"`);
        await queryRunner.query(`DROP TABLE "retailers"`);
        await queryRunner.query(`DROP TYPE "public"."retailers_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."retailers_class_enum"`);
        await queryRunner.query(`DROP TABLE "retailer_channels"`);
        await queryRunner.query(`DROP TABLE "retailer_categories"`);
        await queryRunner.query(`DROP TABLE "scheme_product_categories"`);
        await queryRunner.query(`DROP TABLE "scheme_products"`);
        await queryRunner.query(`DROP TABLE "scheme_retailer_channels"`);
        await queryRunner.query(`DROP TABLE "scheme_retailers"`);
        await queryRunner.query(`DROP TABLE "scheme_slabs"`);
        await queryRunner.query(`DROP TABLE "schemes"`);
        await queryRunner.query(`DROP TABLE "product_pricing_jobs"`);
        await queryRunner.query(`DROP TABLE "product_pricings"`);
        await queryRunner.query(`DROP TABLE "product_flavours"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP TABLE "product_brands"`);
        await queryRunner.query(`DROP TABLE "uoms"`);
        await queryRunner.query(`DROP TABLE "flavours"`);
        await queryRunner.query(`DROP TABLE "product_categories"`);
        await queryRunner.query(`DROP TABLE "stock_transfer_items"`);
        await queryRunner.query(`DROP TABLE "stock_transfers"`);
        await queryRunner.query(`DROP TABLE "stock_balances"`);
        await queryRunner.query(`DROP TABLE "stock_movements"`);
        await queryRunner.query(`DROP TYPE "public"."stock_movements_referencetype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."stock_movements_type_enum"`);
        await queryRunner.query(`DROP TABLE "opening_stock_items"`);
        await queryRunner.query(`DROP TABLE "opening_stocks"`);
        await queryRunner.query(`DROP TABLE "purchase_stock_items"`);
        await queryRunner.query(`DROP TABLE "purchase_stocks"`);
        await queryRunner.query(`DROP TABLE "pjp_routes"`);
        await queryRunner.query(`DROP TABLE "pjp_plans"`);
        await queryRunner.query(`DROP TYPE "public"."pjp_plans_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1ab3aa79ae29d7f99f17c9a4a7"`);
        await queryRunner.query(`DROP TABLE "regions"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
    }

}
